language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "pypy"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libdiscid0
install: python setup.py build
script: ./test_discid.py
